MODEL:
  TYPE: retinanet
  CONV_BODY: FPN.add_fpn_ResNet50_conv5_body
  NUM_CLASSES: 2
NUM_GPUS: 1
SOLVER:
  WEIGHT_DECAY: 0.0001
  LR_POLICY: steps_with_decay
  BASE_LR: 0.001
  GAMMA: 0.1
  MAX_ITER: 20000
  STEPS: [0, 120000, 160000]
FPN:
  FPN_ON: True
  MULTILEVEL_RPN: True
  RPN_MAX_LEVEL: 5
  RPN_MIN_LEVEL: 3
  COARSEST_STRIDE: 32
  EXTRA_CONV_LEVELS: True
RETINANET:
  RETINANET_ON: True
  NUM_CONVS: 4
  ASPECT_RATIOS: (1.0, 2.0, 0.5)
  SCALES_PER_OCTAVE: 3
  ANCHOR_SCALE: 2
  LOSS_GAMMA: 2.0
  LOSS_ALPHA: 0.25
TRAIN:
  SNAPSHOT_ITERS: 1000
  WEIGHTS: models/R-50.pkl
  DATASETS: ('car_detection_train',)
  SCALES: (100,)
  MAX_SIZE: 4000
  RPN_STRADDLE_THRESH: -1  # default 0
TEST:
  DATASETS: ('car_detection_val',)
  SCALE: 1200
  MAX_SIZE: 4000
  NMS: 0.7
  RPN_PRE_NMS_TOP_N: 10000  # Per FPN level
  RPN_POST_NMS_TOP_N: 2000
OUTPUT_DIR: .
